### PR TITLE
Fix 431 PR merge 

### LINKED ISSUE #455: pkg/cmd/logs.go:583:22: undefined: getFromTargetInfo
**Describe the bug**

When i was checking concourse CI build log i found following error:
```
Cloning into 'gardenctl'...
# github.com/gardener/gardenctl/pkg/cmd
pkg/cmd/logs.go:583:22: undefined: getFromTargetInfo
```
https://concourse.ci.gardener.cloud/builds/2410#L5fb7906d:49

This issue is introduced in https://github.com/gardener/gardenctl/pull/431/commits/42c02e6866e7c1ec2ff27a21e164dbfb2e06939b#diff-59f23253994b1605ea49a120ea68de0c2ee3a4240c2825bb741f7b707695211fR582

the method `getFromTargetInfo(string)` has been changed to `func GetFromTargetInfo(targetReader TargetReader, key string)` in https://github.com/gardener/gardenctl/commit/16fc236f9ff027a465d4075eccb2c5c9dd9f9d21

@jguipi could you please look into this? if you need more information regarding above function please reach @tedteng 

Thanks.
-Neo

**To Reproduce**
check concourse ci log

**Expected behavior**
concourse ci build should success

**Screenshots**
image

**Gardenctl Version (please complete the following information):**
latest version in master branch
**Additional context**

### PR DESCRIPTION
**Pull request by jguipi**
**What this PR does / why we need it**:
It resolves PR 431 merge  by using the latest GetFromTargetInfo() method in logsVpnSeed() 

**Which issue(s) this PR fixes**:
Fixes #455 

**Special notes for your reviewer**:
- none
**Release note**:
```improvement operator
- Make logsVpnSeed() use the latest GetFromTargetInfo() method

```

### CODE REVIEW

**Comment by dansible** [comment]
The pipeline is giving this error, can you take a look?
```
 ---> b2f3a7899d6d

Step 2/17 : RUN mkdir -p /go/src/github.com/gardener/gardenctl &&    cd /go/src/github.com/gardener &&    git clone https://github.com/gardener/gardenctl.git &&    cd ./gardenctl &&    CGO_ENABLED=0 GOOS=linux go build -mod=vendor -a -installsuffix cgo -o gardenctl cmd/gardenctl/main.go

 ---> Running in 6776b5611bb7

Cloning into 'gardenctl'...

# github.com/gardener/gardenctl/pkg/cmd

pkg/cmd/logs.go:583:22: undefined: getFromTargetInfo

The command '/bin/sh -c mkdir -p /go/src/github.com/gardener/gardenctl &&    cd /go/src/github.com/gardener &&    git clone https://github.com/gardener/gardenctl.git &&    cd ./gardenctl &&    CGO_ENABLED=0 GOOS=linux go build -mod=vendor -a -installsuffix cgo -o gardenctl cmd/gardenctl/main.go' returned a non-zero code: 2
```

**Review by dansible — APPROVED** [review]
Seems the error is referencing the current master code. Let's merge and retry
